### PR TITLE
fix RayParam resource population

### PR DESCRIPTION
**Pull request by kyle-chen-uber**
small fix about resource population

### CODE REVIEW

**Review by amogkam — APPROVED** [review]
Thanks!

**Comment by amogkam** [comment]
@krfricke do you know whats happening with the CI here? Should we increase the timeout? Or just keep re-trying

**Comment by krfricke** [comment]
I'm not sure why this is failing out of a sudden (it passed previously). But yeah, probably just increasing to 40 minutes is fine.

Mentioning #112 here, which we should address soon.

**Comment by krfricke** [comment]
#117 should fix the test timeouts. I'll then re-run tests here again, and merge afterwards.

**Comment by krfricke** [comment]
Hm doesn't seem to be related to timeouts. It only fails on latest ray master, so there might be incompatible changes there.

Actually, the xgboost-ray/tune release are failing right now, too, so this is probably related.

**Comment by krfricke** [comment]
The failing tests are due to https://github.com/ray-project/ray/issues/16507

This PR should be safe to merge

**Pull request merged**
