### PR TITLE
Remove kill callbacks from colocation tests

### PR DESCRIPTION
**Pull request by krfricke**
This will hopefully deflake the colocation tests

### CODE REVIEW

**Comment by amogkam** [comment]
Hey @krfricke if these tests are flaky with the kill callback, then doesn't that mean there's a problem with the functionality? These should be passing even with worker failures, right?

**Comment by krfricke** [comment]
So the error that comes up is usually that actors cannot be scheduled because resources aren't ready, and this might actually be a core issue. It also seems to come up in the `latest` release and not in the `nightly`.

Generally I'd argue that we want to keep the tests atomic - i.e. if we check colocation, just check colocation. If we check fault tolerance, just check fault tolerance. I'm happy to add another test that combines both but we might want to do this in a separate PR.

**Comment by krfricke** [comment]
(This would probably be just a PR for using Ray Tune + Fault tolerance)

**Review by amogkam — APPROVED** [review]
Got it, makes sense. The tune fault tolerance test sounds like a good idea.

**Pull request merged**
