### PR TITLE
Limit number of parallel GHA runs, print env info in tests

### PR DESCRIPTION
**Pull request by krfricke**
Unfortunately GHA runs are sometimes aborted due to memory limits. Reducing the number of concurrent trials increases our test time to 2x, but at least these errors stop coming up.

### CODE REVIEW

**Comment by krfricke** [comment]
Well, it seems it doesn't solve the problem. Consider this a draft PR, I'll look into how to fix this later

**Review by amogkam — APPROVED** [review]
Interesting- great catch!

**Comment by amogkam** [comment]
Though it still looks like 2 of the jobs are failing.

**Comment by krfricke** [comment]
Yes :-( Maybe we can move this to buildkite?

**Comment by krfricke** [comment]
I don't think this is related to that, the tests were flaky before that change. I mean, we can try, I'll create a revert PR just in case

**Comment by krfricke** [comment]
Doesn't seem to be possible from within GitHub. I might try it manually tomorrow

**Comment by amogkam** [comment]
@krfricke should we merge this?

**Comment by krfricke** [comment]
Yeah let's do it, though it doesn't solve the problem completely. But it is a good start in any case. Thanks for reminding me!

**Pull request merged**
