### PR TITLE
fix detecting dask dataframe for distributed data load

### PR DESCRIPTION
**Pull request by rokrokss**
closes https://github.com/ray-project/xgboost_ray/issues/195

### CODE REVIEW

**Comment by rokrokss** [comment]
@Yard1 could you rerun the test? I had a typo on the commit so rebased it

**Comment by Yard1** [comment]
Ok @rokrokss this looks good! I'll just test this out locally and we should be good to merge.

**Comment by rokrokss** [comment]
@Yard1 Yup, I'm not sure the load_data works right now, I will check that too

**Comment by rokrokss** [comment]
@Yard1 I'm seeing `load_data()` hanging forever with this setting,
sorry that it's hard for me to fix it right now.
but I'll try to use this `RayDMatrix(ray.data.from_dask(df_train), label="label")` for now.

**Comment by Yard1** [comment]
Ok, that's what I am seeing too. Let's just close it for now and put it in the backlog. Thanks for taking the initiative!

**Pull request closed without merging**
